In [3]:
import numpy as np


In [6]:
x=np.array([[1,2,3],[2.4,4.5,3.1],[3.9,5.1,4.9]])
y=np.array([[1],[2],[3]])
alpha=0.1
theta=np.zeros(3).reshape(-1,1)
theta
print('损失函数\n',(y-x.dot(theta)).T.dot(y-x.dot(theta)))
print(theta)

损失函数
 [[14.]]
[[0.]
 [0.]
 [0.]]


In [8]:
#sgd
np.random.seed(10)
#洗牌一样的感觉
np.random.shuffle(x)
np.random.shuffle(y)
print(x)
print(y)
for j in range(100):
    print('xshape',x.shape)
    for i in range(x.shape[0]):
        x_sample=x[i].reshape(-1,1)
        print(x_sample)
        print(x_sample.T)
        print(theta)
        print(x_sample.T.dot(theta))
        y_sample=y[i]
        y_yhat=y_sample-x_sample.T.dot(theta)
        theta=theta+(alpha*y_yhat*x_sample)
        break
    break
print('损失函数\n',(y-x.dot(theta)).T.dot(y-x.dot(theta)))




[[1.  2.  3. ]
 [2.4 4.5 3.1]
 [3.9 5.1 4.9]]
[[1]
 [2]
 [3]]
xshape (3, 3)
[[1.]
 [2.]
 [3.]]
[[1. 2. 3.]]
[[0.]
 [0.]
 [0.]]
[[0.]]
损失函数
 [[0.1793]]


In [9]:
def xiajiang(x,y,theta,num_iter=10,alpha=0.001):
    for i in range(num_iter):
        theta=theta+x.T.dot(y-x.dot(theta))*alpha
        loss=(y-x.dot(theta)).T.dot(y-x.dot(theta))
        print(theta)
        print(loss)

In [11]:
def linear_model(x,y,alpha,yuzhi,max_iter):
    feature_num=x.shape[1]
    theta=np.zeros(feature_num).reshape(-1,1)
    for iter in range(max_iter):
        theta=theta+x.T.dot(y-x.dot(theta))*alpha
        loss=0.5*(y-x.dot(theta)).T.dot(y-x.dot(theta))
        if loss<yuzhi:
            print(loss)
            break
    return theta

def predict(x,theta):
    return x.dot(theta)
    
theta=linear_model(x,y,0.01,0.001,10000)
predict(x,theta)
    


[[0.00099605]]


array([[1.01875159],
       [2.02822242],
       [2.97094893]])

In [12]:
y

array([[1],
       [2],
       [3]])